Repository DS-Volare/front-end, pull requests merged in 2024-08, with the labels that each got.

#39 [Feat/react query api] 로그인 API 연결 및 로컬 스토리지 저장
  package.json
  src/App.tsx
  src/component/base/LoginModal.tsx
  src/component/base/Navbar.tsx
  src/hooks/useAuth.ts
  src/hooks/useUser.ts
  src/page/MainPage.tsx
  src/utils/queryKeys.ts
Labels: Type: Feature

#21 Feat/script component
  src/component/convert/script/SceneItem.tsx
  src/component/convert/script/SceneList.tsx
  src/component/convert/script/ScriptBox.tsx
  src/component/convert/script/scriptDummyData.ts
  src/styles/global.ts
  src/types/index.ts
Labels: Type: Feature

#51 [Feat/main page animation] 메인 페이지 wheel 이벤트, 인디케이터 click 이벤트 발생 시 애니메이션 수행
  src/App.tsx
  src/component/base/Navbar.tsx
  src/component/mainpage/MainIndicator.tsx
  src/context/mainAnimationContext.tsx
  src/hooks/useScreenTransitionAnimation.ts
  src/page/MainPage.tsx
Labels: Type: Feature, Type: Refactor

#49 [Feat/save novel] 소설 저장 ~ 대본 변환 요청까지의 API 연결 및 코드 보완, 웹페이지 동작 개선
  package.json
  src/App.tsx
  src/component/base/Spinner.tsx
  src/component/convert/character/CharacterBox.tsx
  src/component/convert/character/CharacterChipList.tsx
  src/component/convert/novel/NovelBox.tsx
  src/component/convert/script/SceneList.tsx
  src/component/convert/script/ScriptBox.tsx
  src/context/convertDataContext.tsx
  src/hooks/useConvert.ts
  src/page/ConvertPage.tsx
  src/utils/queryKeys.ts
  src/utils/spinnerText.ts
Labels: Type: Feature, Type: Refactor, Type: Design

#55 [Feat/statistics] 변환 정보 마인드맵 구현
  package.json
  src/component/convert/statistics/Mindmap.tsx
  src/component/convert/statistics/StatisticsBox.tsx
Labels: Type: Feature, Type: Design

#58 [Feat/connect api] 캐릭터별 출연률 API 연결, chart.js 적용, 유저 정보 API 연결
  package.json
  src/App.tsx
  src/component/convert/statistics/Mindmap.tsx
  src/component/convert/statistics/RateChart.tsx
  src/component/convert/statistics/StatisticsBox.tsx
  src/hooks/useAuth.ts
  src/hooks/useConvert.ts
  src/page/Mypage.tsx
  src/utils/queryKeys.ts
  src/utils/spinnerText.ts
Labels: Type: Feature

#61 [Fix/chatbot button] 대본화가 완료되었을 때 챗봇 플로팅 버튼 띄우도록 구현
  src/component/convert/chat/ChatbotBox.tsx
  src/utils/toastText.ts
Labels: Type: Feature

#64 [feat] 변환 정보 통계 API 연결
  src/component/convert/statistics/Mindmap.tsx
  src/component/convert/statistics/StatisticsBox.tsx
  src/hooks/useConvert.ts
  src/utils/queryKeys.ts
Labels: Type: Feature
