Repository DS-Volare/front-end, pull requests merged in 2024-10, with the labels that each got.

#69 [Feat/mypage list api] 마이페이지 변환 목록 불러오기
  src/assets/background/list-basic-image.png
  src/component/mypage/Pagenation.tsx
  src/component/mypage/ScriptListCard.tsx
  src/component/mypage/SkeletonListCard.tsx
  src/hooks/useConvert.ts
  src/page/Mypage.tsx
  src/styles/theme.ts
  src/utils/queryKeys.ts
Labels: Type: Feature

#70 [Fix/Design] Design/convert page 등장인물 하이라이트 표시 버그 수정
  src/App.tsx
  src/component/convert/character/CharacterBox.tsx
  src/component/convert/character/characterDummyData.ts
  src/component/mainpage/MainPageSecondBox.tsx
  src/setupProxy.js
  src/styles/global.ts
Labels: Type: BugFix

#75 [design] 통계 컴포넌트 디자인 수정
  src/component/convert/statistics/Mindmap.tsx
  src/component/convert/statistics/RateChart.tsx
Labels: Type: Design

#78 [Feat/create novel] 전시 방문자를 위한 소설 생성 AI 적용
  src/component/base/Navbar.tsx
  src/component/convert/character/CharacterBox.tsx
  src/component/convert/novel/CreateNovelCharacterChip.tsx
  src/component/convert/novel/CreateNovelCharacterChipList.tsx
  src/component/convert/novel/CreateNovelModal.tsx
  src/component/convert/novel/NovelBox.tsx
  src/hooks/useConvert.ts
  src/index.tsx
  src/page/ConvertPage.tsx
  src/styles/convertBoxStyles.ts
  src/utils/queryKeys.ts
  src/utils/spinnerText.ts
Labels: Type: Feature, Type: Design

#76 [Feat/chatbot pagination] 채팅 목록에 커서 기반 페이지네이션 적용 (useInfiniteQuery)
  src/assets/icons/go-back.svg
  src/assets/icons/pencil_center.svg
  src/assets/icons/pencil_icon.svg
  src/assets/icons/send.svg
  src/component/base/Navbar.tsx
  src/component/convert/ConvertIndicator.tsx
  src/component/convert/chat/ChatMessage.tsx
  src/component/convert/chat/ChatbotBox.tsx
  src/component/convert/chat/MessageForm.tsx
  src/component/convert/chat/MessageList.tsx
  src/component/mainpage/MainIndicator.tsx
  src/component/mainpage/MainPageFirstBox.tsx
  src/component/mainpage/MainPageSecondBox.tsx
  src/component/mainpage/MainPageThirdBox.tsx
  src/component/mainpage/SampleNovelSelector.tsx
  src/component/mypage/Pagenation.tsx
  src/component/mypage/ScriptListCard.tsx
  src/hooks/useConvert.ts
  src/page/ConvertPage.tsx
  src/page/MainPage.tsx
  src/page/Mypage.tsx
  src/setupProxy.js
  src/styles/chatbotStyles.ts
  src/styles/convertBoxStyles.ts
  src/styles/mainStyles.ts
  src/utils/queryKeys.ts
Labels: Type: Feature
